name: push_report_service_env
dependencies:
  - python>=3.6,<3.7
  - pip==20.0.2
  - Flask==1.1.1
  - gunicorn==20.0.4
  - pytest==5.3.5
  - gevent==1.4.0
  - pip:
      - --index-url https://pypi.python.org/simple
      - --extra-index-url https://artifactory.outbrain.com/artifactory/api/pypi/ob-pypi/simple
      - obpython==2.0.1
      - flask-restx==0.2.0